HOME:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

WHALE:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

SHARK:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

CORAL:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

DOLPHIN:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

TURTLE:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

OCTOPUS:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

JELLYFISH:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

TUNA:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

FOLLOW:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0

WELCOME:
  x: 0.0
  y: 0.0
  qx: 0.0
  qy: 0.0
  qz: 0.0
  qw: 0.0



 
 
